- platform: mqtt
  name: "Kitchen Main"
  state_topic: "home/status/main/1320"
  command_topic: "home/main/1320"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1320: "OFF"

- platform: mqtt
  name: "Kitchen Lighting"
  state_topic: "home/status/main/1321"
  command_topic: "home/main/1321"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1321: "OFF"

- platform: mqtt
  name: "Guest Zone Light"
  state_topic: "home/status/main/1322"
  command_topic: "home/main/1322"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1322: "OFF"

- platform: mqtt
  name: "Guest Zone Light Left"
  state_topic: "home/status/main/1323"
  command_topic: "home/main/1323"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1323: "OFF"

- platform: mqtt
  name: "Guest Zone Light Right"
  state_topic: "home/status/main/1324"
  command_topic: "home/main/1324"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1324: "OFF"

- platform: mqtt
  name: "Kitchen Venting"  
  state_topic: "home/status/main/1325"
  command_topic: "home/main/1325"
  payload_on: "ON"
  payload_off: "OFF"     
  state_on: "ON"       
  state_off: "OFF"       
  state_1325: "OFF"

- platform: mqtt
  name: "Kitchen Fan"
  state_topic: "home/status/main/1326"
  command_topic: "home/main/1326"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1326: "OFF"

- platform: mqtt
  name: "Kitchen Warm Floor"
  state_topic: "home/status/main/1327"
  command_topic: "home/main/1327"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1327: "OFF"

# Corridor
- platform: mqtt
  name: "Corridor Light"
  state_topic: "home/status/main/1330"
  command_topic: "home/main/1330"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1330: "OFF"

# Toilet
- platform: mqtt
  name: "Toilet Light"
  state_topic: "home/status/main/1331"
  command_topic: "home/main/1331"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1331: "OFF"

- platform: mqtt
  name: "Toilet Fan"
  state_topic: "home/status/main/1332"
  command_topic: "home/main/1332"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1332: "OFF"

# Larder
- platform: mqtt
  name: "Larder Light"
  state_topic: "home/status/main/1333"
  command_topic: "home/main/1333"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1333: "OFF"

- platform: mqtt
  name: "Boiler Water Tap"
  state_topic: "home/status/main/1334"
  command_topic: "home/main/1334"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1334: "OFF"

# Bathroom
- platform: mqtt
  name: "Bathroom Light"
  state_topic: "home/status/main/1335"
  command_topic: "home/main/1335"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1335: "OFF"

- platform: mqtt
  name: "Bathroom Lighting"
  state_topic: "home/status/main/1336"
  command_topic: "home/main/1336"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1336: "OFF"

- platform: mqtt
  name: "Bathroom Fan"
  state_topic: "home/status/main/1337"
  command_topic: "home/main/1337"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  state_1337: "OFF"

